Fix mapping / map update / bootstrap
SolarFramework/SolARFramework pull request #71
Opened 2023-10-30 11:07 UTC by yzhou-bcom

2023-11-02 13:56 UTC, jim-bcom requested changes

2023-11-02 13:56 UTC, jim-bcom commented on interfaces/datastructure/CloudPoint.h
> +    bool isFixedPosition() const;
nit: maybe use grammatically correct names, such as:
```cpp
void setPositionFixed( bool isPositionFixed );
bool isPositionFixed() const;
private:
bool m_isPositionFixed;
```
Or
```cpp
void setFixedPosition( bool hasFixedPosition );
bool hasFixedPosition() const;
private:
bool m_hasFixedPosition;
```

2023-11-07 14:06 UTC, yzhou-bcom commented on interfaces/datastructure/CloudPoint.h
> +    bool isFixedPosition() const;
Thanks jim-bcom, they have been renamed now

2023-11-10 14:43 UTC, jim-bcom approved these changes

2023-11-10 14:47 UTC, merged